baseurl: cougrstats.netlify.app
copyright: Copyright © 2008–2018, Steve Francia and the Hugo Authors; all rights reserved.
paginate: 10
theme: hugo-clarity
disqusShortname: ''
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
DefaultContentLanguage: en
taxonomies:
  category: categories
  series: series
  tag: tags

markup:
  goldmark:
    renderer:
      unsafe: true
