[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Archives"
  url = "post/rich-content/"
  weight = -109

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Links"
  identifier = "Links"
  weight = -108
# [[main]]
#   parent = "Links"
#   name = "LinkedIn"
#   url = "https://www.linkedin.com/"
[[main]]
  parent = "Links"
  name = "Visit us at wsu.edu"
  url = "https://cereo.wsu.edu/r-working-group/"
  weight = 1
[[main]]
  parent = "Links"
  name = "Follow us on Twitter"
  url = "https://twitter.com/cougRstats"
  weight = 2
[[main]]
  parent = "Links"
  name = "View past talks on YouTube"
  url = "https://www.youtube.com/channel/UCycE_sNrSpBNNlHqyoRkNCA"
  weight = 3
[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/cougrstats"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/cougRstats"
[[social]]
  name = "youtube"
  weight = 3
  url = "https://www.youtube.com/channel/UCycE_sNrSpBNNlHqyoRkNCA"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"